name: Benchmark
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 3 * * *"
jobs:
  benchmark:
    if: github.repository == 'hidet-org/hidet'
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true
    runs-on: [self-hosted, Linux, X64, gpu]
    container:
      image: nvidia/cuda:11.8.0-devel-ubuntu20.04
      options: --gpus all
    steps:
      - name: Install dependencies via apt
        run: |
          apt update && DEBIAN_FRONTEND=noninteractive apt install -y ccache git graphviz

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.19.x'

      - name: Install dependencies via pip
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio 
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Build hidet
        run: |
          bash scripts/wheel/build_wheel.sh
          WHEEL=$(find ./scripts/wheel/built_wheel -maxdepth 1 -name '*.whl')
          echo "WHEEL_NAME=$WHEEL" >> $GITHUB_ENV
          echo "Built wheel: ${{ env.WHEEL_NAME }}"

      - name: Install hidet
        run: |
          pip install --no-deps --force-reinstall ${{ env.WHEEL_NAME }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run benchmark
        run: |
          python scripts/ci/benchmark.py --report result.txt --space 2 --git-commit ${{ github.sha }}

      - name: Post result
        uses: peter-evans/create-or-update-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          issue-number: 154
          body-file: ./result.txt
