name: Docs

on:
  push:
    branches: [main]

  pull_request:

jobs:
  docs:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: [self-hosted, Linux, X64, gpu]
    container:
      image: nvidia/cuda:11.8.0-devel-ubuntu20.04
      options: --gpus all
    steps:
      - name: Install dependencies via apt
        run: |
          apt update && apt install -y ccache git

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.19.x'

      - name: Setup Graphviz   # used by sphinx.ext.graphviz
        run: |
          apt install -y graphviz

      - name: Install dependencies via pip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Build hidet
        run: |
          bash scripts/build_wheel.sh
          WHEEL=$(find ./scripts/ -maxdepth 1 -name '*.whl')
          echo "WHEEL_NAME=$WHEEL" >> $GITHUB_ENV
          echo "Built wheel: ${{ env.WHEEL_NAME }}"

      - name: Install hidet
        run: |
          pip install --no-deps --force-reinstall ${{ env.WHEEL_NAME }}


      # Build the docs

      - name: Install docs dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Build docs
        run: |
          cd docs; make clean; make html
